[workspace]
# Cargo should not unify feature flags across dev-dependencies and build
# dependencies. This will be the default behavior in Rust 2021.
resolver = "2"

members = [
  "runtime",
  "proxy", 
  "config"
]

[workspace.dependencies]
anyhow = "1.0"
mimalloc = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"
async-trait="0.1"
pingora = { version = "0.1", features = [ "lb" ] }
serde_yaml = "0.9"
serde = { version="1", features = ["derive"] }
fnv = "1"
http = "1"
notify = "6.1"
matchit = "0.7"

[profile.release]
strip = true
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"