version: '3.8'
services:
  easy-proxy:
    image: ghcr.io/assetsart/easy-proxy:latest
    ports:
      - 8088:8088
    volumes:
      - ./examples:/app/examples
    networks:
      - gateway
  http-echo-1:
    image: hashicorp/http-echo:latest
    command: ["-text", "Hello, World 3002"]
    ports:
      - "3002:5678"
    networks:
      - gateway
  http-echo-2:
    image: hashicorp/http-echo:latest
    command: ["-text", "Hello, World 3003"]
    ports:
      - "3003:5678"
    networks:
      - gateway


networks:
  gateway: {}
