header_selector: x-nylon-proxy

# plugins:
#   - name: plugin_sdk
#     type: ffi
#     file: ./target/examples/go/plugin_sdk.so
#     config:
#       debug: true

services:
  - name: app-service
    service_type: http
    algorithm: round_robin
    endpoints:
      - ip: 127.0.0.1
        port: 3001
      - ip: 127.0.0.1
        port: 3002
    # health_check:
    #   enabled: false
    #   path: /health
    #   interval: 3s
    #   timeout: 1s
    #   healthy_threshold: 2
    #   unhealthy_threshold: 2
