[package]
name = "nylon-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
nylon-abi = { path = "../../abi/rust"}
nylon-ring-host = { workspace = true }
nylon-ring = { workspace = true }
async-trait = { workspace = true }
serde_json =  { workspace = true }
tokio = { workspace = true }
once_cell = { workspace = true }