name: Build and Publish Docker Image

on:
  push:
    branches:
      - release

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/assetsart/easy-proxy:${{ github.sha }} . --push
      - name: Version to latest tag
        run: docker pull ghcr.io/assetsart/easy-proxy:${{ github.sha }}
      - name: Version to latest tag
        run: docker tag ghcr.io/assetsart/easy-proxy:${{ github.sha }} ghcr.io/assetsart/easy-proxy:latest
      - name: Push latest tag to registry
        run: docker push ghcr.io/assetsart/easy-proxy:latest
